---
title: "505 final project"
author: "Bingchu Chen, Xuezhu Zhao"
date: "3/30/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message = FALSE, warning = FALSE)
```

```{r load_packages, warning = FALSE, include=FALSE}
library(sf)
library(lubridate)
library(tigris)
library(tidycensus)
library(viridis)
library(riem)
library(gridExtra)
library(knitr)
library(kableExtra)
library(readxl)
library(gganimate)
library(FNN)
library(tidyverse)
library(ggplot2)
library(dplyr)
library(RSocrata)
library(nngeo)

plotTheme <- function(base_size = 12) {
  theme(
    text = element_text( color = "black"),
    plot.title = element_text(size = 14,colour = "black"),
    plot.subtitle = element_text(face="italic"),
    plot.caption = element_text(hjust=0),
    axis.ticks = element_blank(),
    panel.background = element_blank(),
    panel.grid.major = element_line("grey80", size = 0.1),
    panel.grid.minor = element_blank(),
    panel.border = element_rect(colour = "black", fill=NA, size=2),
    strip.background = element_rect(fill = "grey80", color = "white"),
    strip.text = element_text(size=12),
    axis.title = element_text(size=12),
    axis.text = element_text(size=10),
    plot.background = element_blank(),
    legend.background = element_blank(),
    legend.title = element_text(colour = "black", face = "italic"),
    legend.text = element_text(colour = "black", face = "italic"),
    strip.text.x = element_text(size = 14)
  )
}

nn_function <- function(measureFrom,measureTo,k) {
  measureFrom_Matrix <- as.matrix(measureFrom)
  measureTo_Matrix <- as.matrix(measureTo)
  nn <-   
    get.knnx(measureTo, measureFrom, k)$nn.dist
  output <-
    as.data.frame(nn) %>%
    rownames_to_column(var = "thisPoint") %>%
    gather(points, point_distance, V1:ncol(.)) %>%
    arrange(as.numeric(thisPoint)) %>%
    group_by(thisPoint) %>%
    summarize(pointDistance = mean(point_distance)) %>%
    arrange(as.numeric(thisPoint)) %>%
    dplyr::select(-thisPoint) %>%
    pull()

  return(output)  
}

```


```{r load_data, cache = TRUE, include = FALSE}
meter_loc <- st_read("D:/Upenn/CPLN505/final project/Parking_Meters.csv") 
parking <- read.csv("D:/Upenn/CPLN505/final project/SFMTA_Parking_Meter_Detailed_Revenue_Transactions.csv")
parkingsample <- sample_n(parking, 1000000)%>%
  na.omit()

dat_ymd <- parkingsample %>% 
  mutate(interval60 = floor_date(ymd_hms(SESSION_START_DT), unit = "hour"),
         interval15 = floor_date(ymd_hms(SESSION_START_DT), unit = "15 mins"),
         week = week(interval60),
         dotw = wday(interval60, label=TRUE)) %>%
  filter(week >=44, week <= 48)

study.panel.loc <- 
  parkingsample %>%
  mutate(pk_Counter = 1) %>%
  group_by(POST_ID) %>%
  summarize(pk_Count = sum(pk_Counter, na.rm=T))
study.panel.loc <- merge(x = study.panel.loc, y = meter_loc, by = "POST_ID", all.x=TRUE)

study.panel.t <- 
  dat_ymd %>%
  mutate(pk_Counter = 1) %>%
  group_by(interval60) %>%
  summarize(t_Count = sum(pk_Counter, na.rm=T))

study.panel.loct <- study.panel.loct %>% mutate(hour = hour(interval60))
study.panel.loct <- 
  dat_ymd %>%
  mutate(pk_Counter = 1) %>%
  group_by(POST_ID, interval60) %>%
  summarize(PK_Count = sum(pk_Counter, na.rm=T))
study.panel.loct <- merge(x = study.panel.loct, y = meter_loc, by = "POST_ID", all.x=TRUE) 


hist(study.panel.loc$pk_Count)
study.panel.loc <- study.panel.loc %>% mutate(log.count = log(pk_Count))
hist(study.panel.loc$log.count)
study_panel.sf <- st_as_sf(na.omit(study.panel.loc), coords = c("LONGITUDE", "LATITUDE"), crs = 6339)

hist(study.panel.loct$pk_Count)
study.panel.loc <- study.panel.loc %>% mutate(log.count = log(pk_Count))
hist(study.panel.loc$log.count)
study_panel.sf <- st_as_sf(na.omit(study.panel.loc), coords = c("LONGITUDE", "LATITUDE"), crs = 6339)

```

```{r get_census, message=FALSE, warning=FALSE, cache=TRUE, echo=FALSE, results='hide'}
SFCensus <- 
  get_acs(geography = "tract", 
          variables = c("B01003_001", "B19013_001", 
                        "B02001_002", "B08013_001",
                        "B08012_001", "B08301_001", 
                        "B08301_010", "B01002_001"), 
          year = 2018, 
          state = 06,
          county= 075,
          geometry = TRUE, 
          output = "wide") %>%
  dplyr::rename(Total_Pop =  B01003_001E,
         Med_Inc = B19013_001E,
         Med_Age = B01002_001E,
         White_Pop = B02001_002E,
         Travel_Time = B08013_001E,
         Num_Commuters = B08012_001E,
         Means_of_Transport = B08301_001E,
         Total_Public_Trans = B08301_010E) %>%
  dplyr::select(Total_Pop, Med_Inc, White_Pop, Travel_Time, 
         Means_of_Transport, Total_Public_Trans,
         Med_Age,
         GEOID, geometry) %>%
  mutate(Percent_White = White_Pop / Total_Pop,
         Mean_Commute_Time = Travel_Time / Total_Public_Trans,
         Percent_Taking_Public_Trans = Total_Public_Trans / Means_of_Transport)

SFTracts <- 
  SFCensus %>%
  as.data.frame() %>%
  distinct(GEOID, .keep_all = TRUE) %>%
  #dplyr::select(GEOID, geometry) %>% 
  st_sf %>%
  st_transform(st_crs(6339))

```

```{r load_indp, message=FALSE, warning = FALSE, echo=FALSE, results='hide'}
park <- st_read("https://data.sfgov.org/resource/gtr9-ntp6.geojson") %>%
    mutate(Legend = "park") %>% st_transform(., 6339)

spc_event <- st_read("https://data.sfgov.org/resource/itv4-r6g6.geojson") %>%
    mutate(Legend = "special_event") %>% st_transform(., 6339)

reg_business <- st_read("https://data.sfgov.org/resource/itv4-r6g6.geojson") %>%
    mutate(Legend = "business") %>% st_transform(., 6339)

street_lights <- st_read("https://data.sfgov.org/resource/vw6y-z8j6.geojson") %>% filter(., service_name == "Streetlights") %>%
    mutate(Legend = "street_lights") %>% st_transform(., 6339)

parking_enforcement <- st_read("https://data.sfgov.org/resource/vw6y-z8j6.geojson") %>% filter(., service_name == "Parking Enforcement") %>%
    mutate(Legend = "parking_enforcement") %>% st_transform(., 6339)

#landuse
pdr <- st_read("D:/Upenn/CPLN505/final project/Land_Use.geojson") %>% filter(., landuse == "PDR") %>% mutate(Legend = "dum_pdr") %>% st_transform(., 6339)
retail <- st_read("D:/Upenn/CPLN505/final project/Land_Use.geojson") %>% filter(., landuse == "RETAIL/ENT") %>% mutate(Legend = "dum_retail") %>% st_transform(., 6339)
cultural <- st_read("D:/Upenn/CPLN505/final project/Land_Use.geojson") %>% filter(., landuse == "CIE") %>% mutate(Legend = "dum_culture") %>% st_transform(., 6339)
medical <- st_read("D:/Upenn/CPLN505/final project/Land_Use.geojson") %>% filter(., landuse == "MED") %>% mutate(Legend = "dum_med") %>% st_transform(., 6339)
management <- st_read("D:/Upenn/CPLN505/final project/Land_Use.geojson") %>% filter(., landuse == "MIPS") %>% mutate(Legend = "dum_mgn") %>% st_transform(., 6339)
visitor <- st_read("D:/Upenn/CPLN505/final project/Land_Use.geojson") %>% filter(., landuse == "VISITOR") %>% mutate(Legend = "dum_vis") %>% st_transform(., 6339)

school <- st_read("https://data.sfgov.org/resource/tpp3-epx2.geojson") %>% mutate(Legend = "school") %>% st_transform(., 6339)
college <- st_read("https://data.sfgov.org/resource/8r3f-pc6a.geojson") %>% mutate(Legend = "college") %>% st_transform(., 6339)

transitstop <- st_read("https://opendata.arcgis.com/datasets/561dc5b42fa9451b95faf615a3054260_0.geojson") %>% mutate(Legend = "transit") %>% st_transform(., 6339)
historic_resources <- st_read("https://data.sfgov.org/resource/3tsw-4idn.geojson") %>% mutate(Legend = "historic_rcs") %>% st_transform(., 6339)
reg_historical <- st_read("https://data.sfgov.org/resource/tvzs-3qce.geojson") %>% mutate(Legend = "historical_dist") %>% st_transform(., 6339)


#weather
weather.Panel <- 
  riem_measures(station = "SFO", date_start = "2017-07-05", date_end = "2017-08-04") %>%
  dplyr::select(valid, tmpf, p01i, sknt, vsby)%>% #add visibility in miles
  replace(is.na(.), 0) %>%
    mutate(interval60 = ymd_h(substr(valid,1,13))) %>%
    mutate(week = week(interval60),
           dotw = wday(interval60, label=TRUE)) %>%
    group_by(interval60) %>%
    summarize(Temperature = max(tmpf),
              Precipitation = sum(p01i),
              Wind_Speed = max(sknt),
              visibility = max(vsby)) %>%
    mutate(Temperature = ifelse(Temperature == 0, 42, Temperature))

grid.arrange(
  ggplot(weather.Panel, aes(interval60,Precipitation)) + geom_line() + 
  labs(title="Percipitation", x="Hour", y="Perecipitation") + plotTheme(),
  ggplot(weather.Panel, aes(interval60,Wind_Speed)) + geom_line() + 
    labs(title="Wind Speed", x="Hour", y="Wind Speed") + plotTheme(),
  ggplot(weather.Panel, aes(interval60,Temperature)) + geom_line() + 
    labs(title="Temperature", x="Hour", y="Temperature") + plotTheme(),
  ggplot(weather.Panel, aes(interval60,Temperature)) + geom_line() + 
    labs(title="Visibility", x="Hour", y="Temperature") + plotTheme(),
  top="Weather Data - San Francisco SFO - July/August, 2017")
```

```{r transform, message=FALSE, warning = FALSE, echo=FALSE, results='hide'}
st_c <- st_coordinates
st_coid <- st_centroid

vars_nn <- #some data is not working
  study_panel.sf %>%
    mutate(
      #park.nn =
        #nn_function(st_c(study_panel.sf), st_c(park),1),
      spc_event.nn =
        nn_function(st_c(study_panel.sf), st_c(st_coid(spc_event)),1),
      reg_business.nn =
        nn_function(st_c(study_panel.sf), st_c(st_coid(reg_business)),1),
      lights.nn =
        nn_function(st_c(study_panel.sf), st_c(street_lights),2),
      enforcement.nn =
        nn_function(st_c(study_panel.sf), st_c(parking_enforcement),3),
      school.nn =
        nn_function(st_c(study_panel.sf), st_c(school),1),
      college.nn =
        nn_function(st_c(study_panel.sf), st_c(college),1),
      transitstop.nn =
        nn_function(st_c(study_panel.sf), st_c(transitstop),1),
      historic_resources.nn =
        nn_function(st_c(study_panel.sf), st_c(st_coid(historic_resources)),1),
      reg_historical.nn =
        nn_function(st_c(study_panel.sf), st_c(st_coid(reg_historical)),1)
      )

study_panel.sf <- st_transform(study_panel.sf, 6339)
park <- st_transform(park, 6339)
nnpark <- st_nn(study_panel.sf, park, returnDist = TRUE)

plot(st_geometry(study_panel.sf.sp))

vars_dummy <- 
  study_panel.sf %>%
    mutate(
      pdr = ifelse(st_intersects(study_panel.sf, pdr), 1, 0),
      retail = ifelse(st_intersects(study_panel.sf, retail), 1, 0),
      cultural = ifelse(st_intersects(study_panel.sf, cultural), 1, 0),
      medical = ifelse(st_intersects(study_panel.sf, medical), 1, 0),
      management = ifelse(st_intersects(study_panel.sf, management), 1, 0),
      visitor = ifelse(st_intersects(study_panel.sf, visitor), 1, 0)
    )

install.packages("spatialEco")
library(spatialEco)
install.packages("sp")
library(sp)
vars_tract <- point.in.poly(study_panel.sf, SFTracts)#, sp = FALSE, duplicate = FALSE)
nnpark.df <- data.frame(do.call(rbind,nnpark[[1]]),do.call(rbind,nnpark[[2]]))
write.csv(nnpark.df, "nnpark.csv")#4199249 for all??

```

```{r explore}
par(mfrow=c(3,3))
hist(vars_nn$spc_event.nn)
hist(vars_nn$reg_business.nn)
hist(vars_nn$lights.nn)
hist(vars_nn$enforcement.nn)
hist(vars_nn$school.nn)
hist(vars_nn$college.nn)
hist(vars_nn$transitstop.nn)
hist(vars_nn$historic_resources.nn)
hist(vars_nn$reg_historical.nn)

hist(as.numeric(vars_tract$Med_Inc))

ggplot(vars_dummy) + geom_bar(aes(x = cultural))
```


Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
